language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - sysimg-22
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
branches:
  only:
    - gh-pages
before_install:
  - android list sdk --no-ui --all -extended
script: ./android_commons_test.sh
