language: android
android:
  components:
    - build-tools-22.0.1
    - build-tools-21.1.2
    - build-tools-21.1.1
    - build-tools-19.1.0
    - android-22
    - android-21
    - android-19
    - platform-tools
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - '.*intel.+'
branches:
  only:
    - gh-pages
# before_install:
#   - android list sdk --no-ui --all -extended
script: ./android_commons_test.sh
